export { default as SimpleText } from './SimpleText'
export { default as CompanyLogos } from './CompanyLogos'
export { default as DisclaimerBanner } from './DisclaimerBanner'
export { default as FaqSection } from './FaqSection'
export { default as FormContact } from './FormContact'
export { default as FormMailing } from './FormMailing'
export { default as FullwidthImage } from './FullwidthImage'
export { default as ImageHero } from './ImageHero'
export { default as ImageCarousel } from './ImageCarousel'

export { default as MainFooter } from './MainFooter'
export { default as MainNavigation } from './MainNavigation'
export { default as PricingCards } from './PricingCards'